use_frameworks!

target 'This_Example' do
  pod 'This', :path => 'https://github.com/chrisbkarani/ThisKit.git'

  target 'This_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
